### PR TITLE
Add failing test case for new-lines

### PR DESCRIPTION
**Pull request by Gregoor**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

Hi there,

thanks for putting all the work into this. I found a case where this lib diverges from `innerText` and added a test case for it. If you agree that it should behave differently, I'd be happy to also work on a fix.

### CODE REVIEW

**Comment by wooorm** [comment]
Hi there!

What is the reason you used a space, instead of a line feed?
If I run this code:

```js
const $div = document.createElement('div')
const $span = document.createElement('span')
$div.appendChild(document.createTextNode('alpha\n'))
$div.appendChild($span)
$span.appendChild(document.createTextNode('bravo'))
console.log($div.innerText)
```

I get:

```text
alpha
bravo
```

**Comment by wooorm** [comment]
ah, it makes more sense to add it to the dom, which does use the space:

```js
const $div = document.createElement('div')
const $span = document.createElement('span')
$div.appendChild(document.createTextNode('alpha\n'))
$div.appendChild($span)
$span.appendChild(document.createTextNode('bravo'))

document.body.innerHTML = ''
document.body.appendChild($div)

document.body.innerText
```

```
alpha bravo
```

**Comment by Gregoor** [comment]
I could have also added a fiddle, for completeness sake, here is one: https://jsfiddle.net/L5y31gxc/ (though I see you also reproduced it already)

**Comment by wooorm** [comment]
Hmm, I looked into it for a while. Here are some more tests:

```diff
+  t.equal(
+    toText(h('p', ['A\n', h('span', 'b')])),
+    'A b',
+    'should support line endings around element breaks (1)'
+  )
+
+  t.equal(
+    toText(h('p', ['A\nb', h('span', 'c')])),
+    'A bc',
+    'should support line endings around element breaks (2)'
+  )
+
+  t.equal(
+    toText(h('p', ['A', h('span', '\nb')])),
+    'A b',
+    'should support line endings around element breaks (3)'
+  )
+
+  t.equal(
+    toText(h('p', ['A\n', h('span', '\nb')])),
+    'A b',
+    'should support line endings around element breaks (4)'
+  )
+
+  t.equal(
+    toText(h('p', [h('span', 'A\n'), h('span', 'b')])),
+    'A b',
+    'should support line endings around element breaks (5)'
+  )
+
+  t.equal(
+    toText(h('p', [h('span', 'A'), h('span', '\nb')])),
+    'A b',
+    'should support line endings around element breaks (6)'
+  )
+
+  t.equal(
+    toText(h('p', [h('span', 'A\n'), h('span', '\nb')])),
+    'A b',
+    'should support line endings around element breaks (7)'
+  )
+
+  t.equal(
+    toText(h('p', [h('span', 'A\n'), 'b'])),
+    'A b',
+    'should support line endings around element breaks (8)'
+  )
+
+  t.equal(
+    toText(h('p', [h('span', 'A'), '\nb'])),
+    'A b',
+    'should support line endings around element breaks (9)'
+  )
+
+  t.equal(
+    toText(h('p', [h('span', 'A\n'), '\nb'])),
+    'A b',
+    'should support line endings around element breaks (10)'
+  )
+
+  t.equal(
+    toText(h('div', [h('p', [h('span', 'A\n'), '\nb'])])),
+    'A b',
+    'should support line endings around element breaks (11)'
+  )
+
```

For a solution, there are two parts. The first loop in `collectText` is incorrect, and the correct break{before/after} should be given:

```diff
-  while (start < value.length) {
+  while (start <= value.length) {
     searchLineFeeds.lastIndex = start
     match = searchLineFeeds.exec(value)
     // @ts-expect-error: `index` is set.
     end = match ? match.index : value.length
-
-    lines.push(
-      // Any sequence of collapsible spaces and tabs immediately preceding or
-      // following a segment break is removed.
-      trimAndCollapseSpacesAndTabs(
-        // [...] ignoring bidi formatting characters (characters with the
-        // Bidi_Control property [UAX9]: ALM, LTR, RTL, LRE-RLO, LRI-PDI) as if
-        // they were not there.
-        value
-          .slice(start, end)
-          .replace(/[\u061C\u200E\u200F\u202A-\u202E\u2066-\u2069]/g, ''),
-        options.breakBefore,
-        options.breakAfter
-      )
-    )
-
+    lines.push(value.slice(start, end))
     start = end + 1
   }
 
+  lines = lines.map((line, i) =>
+    // Any sequence of collapsible spaces and tabs immediately preceding or
+    // following a segment break is removed.
+    trimAndCollapseSpacesAndTabs(
+      // […] ignoring bidi formatting characters (characters with the
+      // Bidi_Control property [UAX9]: ALM, LTR, RTL, LRE-RLO, LRI-PDI) as if
+      // they were not there.
+      line.replace(/[\u061C\u200E\u200F\u202A-\u202E\u2066-\u2069]/g, ''),
+      i === 0 ? options.breakBefore : true,
+      i === lines.length - 1 ? options.breakAfter : true
+    )
+  )
+
```

Second, is add a space at the start/end, if a line ending is found, and there is no break before/after.
When one is added, that should also affect the next node: it doesn’t need one anymore.
This last part is a bit similar to https://github.com/rehypejs/rehype-minify/commit/64c6206f2ac5c25a4465966a6e29ac696ed63f8b#diff-1b9ff2153d4d4ef101fc2ade7c5df0bf95f910b7e1294785fc0d2d86fdebfa88.

**Comment by wooorm** [comment]
Found it! :)

**Pull request closed without merging**
